spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xiandanpro?characterEncoding=utf-8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8088
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
#mybatis
mybatis-plus:
  type-aliases-package: com.huang.*.entity
  mapper-locations: classpath*:xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_null

#xiandan程序配置
xiandan:
  domain-name: http://localhost:8088
  resources:
    page:
      pageSize: 10
    picture:
      picUrl: /images/
      path: D:\Xiandan\images\
  appid: "wx75f01b18b5b42af9"
  secret: "da8dffbceb895b7080c4eaf2c2cb316e"